### ISSUE TITLE
Change order of subskills affects production output

### ISSUE THREAD

**Issue by IstrajI** [SleepAPI/SleepAPI#242]
### Environment

Production (https://sleepapi.net/)

### Steps to Reproduce

Hello!
I'me faced that changing order of subskills in params for `https://api.sleepapi.net/api/calculator/production/`
results in difference of berry output (others params like spilled ingredients too)

I've used Arbok with code

`{
  "level": 30,
  "nature": "Lonely",
  "subskills": [
    "Berry Finding S", "Helping Speed M", "Helping Speed S"
  ],
  "e4eProcs": 10,
  "e4eLevel": 6,
  "cheer": 0,
  "extraHelpful": 0,
  "helperBoostProcs": 10,
  "helperBoostUnique": 5,
  "helperBoostLevel": 6,
  "helpingbonus": 4,
  "camp": true,
  "erb": 5,
  "recoveryIncense": false,
  "skillLevel": 7,
  "mainBedtime": "21:30",
  "mainWakeup": "06:00",
  "ingredientSet": [
    "Sausage", "Egg"
  ]
}`

And changing subskills to 

` "subskills": [
    "Berry Finding S", "Helping Speed S", "Helping Speed M"
  ],`
  
leads to berries diff from  513 to 485

Also could you please share wich is correct order, before fix goes in?

### Expected Result

Changing order doesn't affect production output

### Actual Result

Change order of subskills affect production output

**Comment by SleepAPI** [comment]
Hello @IstrajI, thank you for your question. This is working as expected. The API takes a list of subskills and then a level number. The backend will take the first X subskills from the input array depending on how many you have access to for your current level. 

In your case you have sent in 3 subskills for a level 30 Arbok, but at level 30 we only have access to 2 subskills. Thus the backend will take the first 2 subskills from the list and use those. If you bump level to 50 then you'll find that swapping the order no longer affects the results since all 3 subskills will now be used. 

Let me know if you have follow-up questions 👍

**Comment by IstrajI** [comment]
Ha, thanks, I've missed up again :D
